core/urls.py
from django.urls import path

from .views import HomeView, ContactView, email


app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('email/', email, name='email'),

]

shop/urls.py
from django.urls import path

from shop.views import (ShopView,
                        ProductSingleView, 
                        CartView, 
                        CheckoutView,
                        PaymentView,
                        add_to_cart,
                        add_one_to_cart,
                        remove_one_from_cart,
                        remove_from_cart)
app_name = 'shop'

urlpatterns = [
    path('<category>/', ShopView.as_view(), name='shop'),
    path('product-single/<slug>/', ProductSingleView.as_view(), name='product_single'),
    path('cart', CartView.as_view(), name='cart'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('add-one-to-cart/<slug>/', add_one_to_cart, name='add-one-to-cart'),
    path('remove-one-from-cart/<slug>/', remove_one_from_cart, name='remove-one-from-cart'),
    path('checkout', CheckoutView.as_view(), name='checkout'),
    path('payment', PaymentView.as_view(), name='payment'),
]

templates/forall/_footer.html
{% load static %}
<footer class="ftco-footer ftco-section img" style="background-image: url({% static 'images/bg_5.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row mb-5">
            <div class="col-lg-5 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">About Us</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Services</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Cooked</a></li>
                        <li><a href="#" class="py-2 d-block">Deliver</a></li>
                        <li><a href="#" class="py-2 d-block">Quality Foods</a></li>
                        <li><a href="#" class="py-2 d-block">Mixed</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li>
                                <span class="icon icon-map-marker"></span>
                                <span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="icon icon-phone"></span>
                                    <span class="text">+2 392 3929 210</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="icon icon-envelope"></span>
                                    <span class="text">info@yourdomain.com</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>
                        document.write(new Date().getFullYear());
                    </script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

templates/forall/_link_files.html
{% load static %}

<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">


<link rel="stylesheet" href= {% static "css/open-iconic-bootstrap.min.css" %} >
<link rel="stylesheet" href= {% static "css/animate.css" %}>

<link rel="stylesheet" href= {% static "css/owl.carousel.min.css" %}>
<link rel="stylesheet" href= {% static "css/owl.theme.default.min.css" %}>
<link rel="stylesheet" href= {% static "css/magnific-popup.css" %}>

<link rel="stylesheet" href= {% static "css/aos.css" %}>

<link rel="stylesheet" href= {% static "css/ionicons.min.css" %}>

<link rel="stylesheet" href= {% static "css/bootstrap-datepicker.css" %}>
<link rel="stylesheet" href= {% static "css/jquery.timepicker.css" %}>


<link rel="stylesheet" href= {% static "css/flaticon.css" %}>
<link rel="stylesheet" href= {% static "css/icomoon.css" %}>
<link rel="stylesheet" href= {% static "css/style.css" %}>

templates/forall/_loader_snippet.html
<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" />
    </svg>
</div>

templates/forall/_map_snippet.html
<section class="ftco-appointment">
    <div class="overlay"></div>
    <div class="container-wrap">
        <div class="row no-gutters d-md-flex align-items-center">
            <div class="col-md-12 d-flex align-self-stretch">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3539.882651217452!2d41.673941814567016!3d27.47291248288961!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x15763f4c7c17e39d%3A0x9629b3339e812118!2sCenter%20Point!5e0!3m2!1sen!2sin!4v1593492786738!5m2!1sen!2sin" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
        </div>
    </div>
</section>

templates/forall/_messages.html
{% if messages %}
        <div class="alert-container mt-5 pt-5">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </div>
{% endif %}

templates/forall/_nav_header.html
{% load cart_template_tags %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="container">
        <a class="navbar-brand" href={% url 'core:home' %}>Coffee<small>Station</small></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item {% if home %}active{% endif %}"><a href={% url 'core:home' %} class="nav-link">Home</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="room.html" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Shop</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                        <a class="dropdown-item" href={% url 'shop:shop' 'coffee-machines' %}>Coffee Machines</a>
                        <a class="dropdown-item" href={% url 'shop:shop' 'coffee-tools' %}>Coffee Tools</a>
                        <a class="dropdown-item" href={% url 'shop:shop' 'coffee-cups' %}>Coffee Cups</a>
                        <a class="dropdown-item" href={% url 'shop:shop' 'imported-coffee' %}>Imported Coffee</a>
                    </div>
                </li>
                <li class="nav-item {% if contact %}active{% endif %}"><a href={% url 'core:contact' %} class="nav-link">Contact</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item cart">
                    <a href={% url 'shop:cart' %} class="nav-link">
                        <span class="icon icon-shopping_cart"></span>
                        <span class="bag d-flex justify-content-center align-items-center">
                            <small>{{ user | cart_items_count}}</small>
                        </span>
                    </a>
                </li>
                
                <li class="nav-item"><a href="{% url 'account_logout' %}" class="nav-link">Sign Out</a></li>
                {% else %}
                <li class="nav-item" ><a href="{% url 'account_login' %}" class="nav-link">Sign In</a></li>
                <li class="nav-item" ><a href="{% url 'account_signup' %}" class="nav-link">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/forall/_related_products_snippet.html
{% load static %}

<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
            <div class="col-md-7 heading-section ftco-animate text-center">
                <span class="subheading">Discover</span>
                <h2 class="mb-4">Related products</h2>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="menu-entry">
                    <a href="/shop/product-single/breville-barista-express-espresso-machine/" class="img" style="background-image: url({% static 'images/related_products_1.jpg' %});"></a>
                    <div class="text text-center pt-4">
                        <h3><a href="/shop/product-single/breville-barista-express-espresso-machine/">Breville Esspresso</a></h3>
                        <p>A small river named Duden flows by their place and supplies</p>
                        <p class="price"><span>$200</span></p>
                        <p><a href="/shop/add-to-cart/breville-barista-express-espresso-machine/" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="menu-entry">
                    <a href="/shop/product-single/drop-coffee/" class="img" style="background-image: url({% static 'images/related_products_2.jpg' %});"></a>
                    <div class="text text-center pt-4">
                        <h3><a href="/shop/product-single/drop-coffee/">Drop Coffee</a></h3>
                        <p>A small river named Duden flows by their place and supplies</p>
                        <p class="price"><span>$5.90</span></p>
                        <p><a href="/shop/add-to-cart/drop-coffee/" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="menu-entry">
                    <a href="/shop/product-single/labarre-bookstore-cafe/" class="img" style="background-image: url({% static 'images/related_products_3.jpg' %});"></a>
                    <div class="text text-center pt-4">
                        <h3><a href="/shop/product-single/labarre-bookstore-cafe/">Labare Coffee Cups</a></h3>
                        <p>A small river named Duden flows by their place and supplies</p>
                        <p class="price"><span>$10.90</span></p>
                        <p><a href="/shop/add-to-cart/labarre-bookstore-cafe/" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="menu-entry">
                    <a href="/shop/product-single/tea-teapot-pot/" class="img" style="background-image: url({% static 'images/related_products_4.jpg' %});"></a>
                    <div class="text text-center pt-4">
                        <h3><a href="/shop/product-single/tea-teapot-pot/">Tea Teapot Pot</a></h3>
                        <p>A small river named Duden flows by their place and supplies</p>
                        <p class="price"><span>$80</span></p>
                        <p><a href="/shop/add-to-cart/tea-teapot-pot/" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/forall/_script_files.html
{% load static %}

<script src= {% static "js/jquery.min.js" %}></script>
<script src= {% static "js/jquery-migrate-3.0.1.min.js" %}></script>
<script src= {% static "js/popper.min.js" %}></script>
<script src= {% static "js/bootstrap.min.js" %}></script>
<script src= {% static "js/jquery.easing.1.3.js" %}></script>
<script src= {% static "js/jquery.waypoints.min.js" %}></script>
<script src= {% static "js/jquery.stellar.min.js" %}></script>
<script src= {% static "js/owl.carousel.min.js" %}></script>
<script src= {% static "js/jquery.magnific-popup.min.js" %}></script>
<script src= {% static "js/aos.js" %}></script>
<script src= {% static "js/jquery.animateNumber.min.js" %}></script>
<script src= {% static "js/bootstrap-datepicker.js" %}></script>
<script src= {% static "js/jquery.timepicker.min.js" %}></script>
<script src= {% static "js/scrollax.min.js" %}></script>
<script src= {% static "js/main.js" %}></script>

templates/forall/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/ico" href={% static 'favicon.ico' %}/>
    <title>
        {% block page_title %}
            Coffee Station
        {% endblock page_title %}
    </title>

    {% include "forall/_link_files.html" %} 
    <style>
        .owl-carousel.owl-drag .owl-item{
            touch-action: manipulation;
        }
    </style>
    {% block pageSpecificCSS %} 
    {% endblock pageSpecificCSS %}

</head>

<body>

    {% include 'forall/_nav_header.html' %} 

    
   {% include 'forall/_messages.html' %} 
    
    
    {% block content %} 
    {% endblock content %} 
    
    {% include 'forall/_footer.html' %} 
    
    {% include 'forall/_loader_snippet.html' %} 
    
    {% include 'forall/_script_files.html' %} 

    <script>
        const alertp = document.querySelector('.alert-container')
        const close = document.querySelector('.alert button.close')
        close.addEventListener('click', ()=>{
            $('.alert-container').slideUp("slow")
        })
        
    </script>

    {% block pageSpecificJS %} 
    {% endblock pageSpecificJS %}

</body>

</html>