core/urls.py
from django.urls import path

from .views import HomeView, ContactView, email


app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('email/', email, name='email'),

]

shop/urls.py
from django.urls import path

from shop.views import (ShopView,
                        ProductSingleView, 
                        CartView, 
                        CheckoutView,
                        PaymentView,
                        add_to_cart,
                        add_one_to_cart,
                        remove_one_from_cart,
                        remove_from_cart)
app_name = 'shop'

urlpatterns = [
    path('<category>/', ShopView.as_view(), name='shop'),
    path('product-single/<slug>/', ProductSingleView.as_view(), name='product_single'),
    path('cart', CartView.as_view(), name='cart'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('add-one-to-cart/<slug>/', add_one_to_cart, name='add-one-to-cart'),
    path('remove-one-from-cart/<slug>/', remove_one_from_cart, name='remove-one-from-cart'),
    path('checkout', CheckoutView.as_view(), name='checkout'),
    path('payment', PaymentView.as_view(), name='payment'),
]

shop/forms.py
from django import forms
from allauth.account.forms import SignupForm
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

class CheckoutForm(forms.Form):
    PAYMENT_CHOICES = (
        ('S','Stripe'),
        ('P','Paypal'),
    )

    first_name = forms.CharField(required=False,
                                max_length=20,
                                widget=forms.TextInput(
                                    attrs={'class':'form-control'}
                                 ))
    last_name = forms.CharField(max_length=20, required=False,
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control'}
                                ))
    phone = forms.CharField(max_length=15, required=False,
                            widget=forms.TextInput(
                                attrs={'class':'form-control',
                                }
                            ))
    email = forms.EmailField(required=False,
                             widget=forms.EmailInput(
                                attrs={'class': 'form-control'}
                             ))
    street_name = forms.CharField(max_length=30, required=False,
                                  widget=forms.TextInput(
                                    attrs={'class': 'form-control'}
                                  ))
    apartment = forms.CharField(max_length=30, required=False,
                            widget=forms.TextInput(
                                attrs={'class': 'form-control'}
                            ))
    city = forms.CharField(max_length=20,
                            required=False,
                           widget=forms.TextInput(
                               attrs={'class': 'form-control'}
                           ))
    zipcode = forms.CharField(max_length=6, required=False,
                            widget=forms.TextInput(
                                attrs={'class':'form-control'}
                            ))
    country = CountryField(blank_label='--SELECT COUNTRY--').formfield(required=False,
                            widget=CountrySelectWidget(
                                attrs={'class':'form-control'}
                            ))
    set_default = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)

    # payment_choice = forms.ChoiceField(choices=PAYMENT_CHOICES,
    #                                    widget=forms.RadioSelect(
    #                                     attrs={'class':'mr-2'}
    #                                    )
    #                                 )

# class MySignupForm(SignupForm):
#     username = forms.CharField(max_length=30, required=True,
#                                widget=forms.TextInput(
#                                    attrs={
#                                        'class': 'form-control',
#                                         'placeholder':'Username'}
#                                ))

#     email = forms.CharField(max_length=30, required=False,
#                                widget=forms.EmailInput(
#                                    attrs={
#                                        'class': 'form-control',
#                                        'placeholder': 'Enter your Email'}
#                                ))
#     password = forms.CharField(max_length=30, required=False,
#                                widget=forms.PasswordInput(
#                                    attrs={
#                                        'class': 'form-control',
#                                        'placeholder': 'Password'}
#                                ))
#     passwordc = forms.CharField(max_length=30, required=False,
#                                 widget=forms.PasswordInput(
#                                     attrs={
#                                         'class': 'form-control',
#                                         'placeholder':'Confirm Password'}
#                                 ))


#     def signup(self, request, user):
#         user.username = self.cleaned_data['username']
#         user.email = self.cleaned_data['email']
#         user.password = self.cleaned_data['password']
#         user.passwordc = self.cleaned_data['passwordc']
#         user.save()
#         return user

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, View
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

from .models import Category, Item, OrderItem, Order, Payment
from core.models import Address

from .forms import CheckoutForm

import stripe

def is_valid_form(values):
    valid = True
    for value in values:
        if value == '':
            valid = False
            return valid
    return valid

class ShopView(ListView):
    
    def get(self, *args, **kwargs):
        
        category = self.kwargs['category']
        c=''
        if category == 'coffee-machines':
            c = 'CM'
        if category == 'coffee-tools':
            c = 'CT'
        if category == 'coffee-cups':
            c = 'CC'
        if category == 'imported-coffee':
            c = 'IC'

        context = {
            'categories': Category.objects.all(),
            'items': Item.objects.filter(category=c),
            'category_param': category,
            'shop':True
        }
        return render(self.request, 'shop.html', context)
    
    

class ProductSingleView(ListView):

    def get(self, *args, **kwargs):

        slug = self.kwargs['slug']
        context = {
            'slug': slug,
            'item': Item.objects.get(slug=slug),
        }
        return render(self.request, 'product-single.html', context)


class CartView(LoginRequiredMixin, View):

   def get(self, *args, **kwargs):
       cart_items = Order.objects.filter(user=self.request.user, is_ordered=False)

       if cart_items.exists():
           
            context = {
                'cart_items': cart_items[0],
                'cart': True
            }
            
            return render(self.request, 'cart.html', context)
       else:
            messages.info(self.request, "No products available. Redirecting to homepage")
            # add template 404 
            return redirect("core:home")

@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        is_ordered=False
    )

    order_qs = Order.objects.filter(user=request.user, is_ordered=False)
   
    if order_qs.exists():
        order = order_qs[0]

        if order.items.filter(user=request.user, is_ordered=False):
            order_item.quantity += 1
            order_item.save()
            order.items.add(order_item)
            messages.info(request, "This item has been updated!")
            return redirect("shop:cart")
        else:
            order_item.quantity = 1
            order_item.save()
            messages.info(request, "This item has been added to cart!")
            order.items.add(order_item)
            return redirect("shop:cart")
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user=request.user,
            ordered_date=ordered_date,
        )
        messages.info(request, "This item has been added to cart!")
        order.items.add(order_item)
        return redirect("shop:cart")
    
@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)

    order_qs = Order.objects.filter(user=request.user, is_ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.items.filter(user=request.user, is_ordered=False):
            order_item = OrderItem.objects.filter(
                item=item,
                is_ordered=False,
                user=request.user
            )[0]

            order_item.quantity = 1
            order_item.save()
            messages.info(request, "This item has been removed from your cart!")
            order.items.remove(order_item)
            return redirect("shop:cart")
        else:
            messages.info(request, "This item is not in your cart!")
            return redirect("shop:cart")
    else:
        message(request, "You don't have any order yet!")
        return redirect("shop:shop",  category="category-cmt")


@login_required
def add_one_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)

    order_qs = Order.objects.filter(user=request.user, is_ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                is_ordered=False,
                user=request.user
            )[0]

            order_item.quantity += 1
            order_item.save()
            data = {
                'quantity': order_item.quantity,
            }
            return JsonResponse(data)
        else:
            messages.info(request, "This item is not in your cart!")
            return redirect("shop:cart")
    else:
        messages.info(request, "You don't have any order yet!")
        return redirect("shop:shop", category="category-cmt")

@login_required
def remove_one_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)

    order_qs = Order.objects.filter(user=request.user, is_ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                is_ordered=False,
                user=request.user
            )[0]
            
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                data={
                    'quantity': order_item.quantity,
                }
                return JsonResponse(data)
            else:
                print("inside iffff")
                messages.info(request, "This item has been removed from your cart!")
                order_item.quantity -= 1
                order_item.save()
                order.items.remove(order_item)
                # return redirect("shop:shop", category="coffee-machines")
                data = {
                    'quantity': order_item.quantity,
                }
                return JsonResponse(data)
        else:
            messages.info(request, "This item is not in your cart!")
            return redirect("shop:cart")
    else:
        messages.info(request, "You don't have any order yet!")
        return redirect("shop:shop", category="category-cmt")

class CheckoutView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        
        order_qs = Order.objects.filter(user=self.request.user, is_ordered=False)

        if order_qs.exists():
            order = order_qs[0]

            form = CheckoutForm()
            
            context = {
                'order': order,
                'form': form,
                'checkout':True
            }
            return render(self.request, "checkout.html", context)
        else:
            messages.info(self.request, "No products available. Redirecting to homepage.")
            # add template 404
            return redirect("core:home")
    
    def post(self, *args, **kwargs):

        form = CheckoutForm(self.request.POST or None)

        try:
            order = Order.objects.filter(user=self.request.user, is_ordered=False)[0]

            if form.is_valid():
                use_default = form.cleaned_data.get('use_default')
                
                if use_default:
                    address_qs = Address.objects.filter(user=self.request.user,
                                                        default=True,
                                                        address_type='B')
                    if address_qs.exists():
                        address = address_qs[0]
                        order.billing_address = address
                        order.save()
                    else:
                        messages.info(self.request, "No default address available!")
                        return redirect("shop:checkout")
                else:
                    street_address = form.cleaned_data.get('street_name')
                    apartment_address = form.cleaned_data.get('apartment')
                    country = form.cleaned_data.get('country')
                    zipcode = form.cleaned_data.get('zipcode')

                    if is_valid_form([street_address, country, zipcode]):
                        address = Address(
                            user=self.request.user,
                            street_address=street_address,
                            apartment_address=apartment_address,
                            country=country,
                            zipcode=zipcode,
                            address_type='B'
                        )

                        address.save()
                        order.billing_address = address
                        order.save()

                        set_default = form.cleaned_data.get('set_default')
                        if set_default:
                            address.default = True
                            address.save()
                    else:
                        messages.warning(self.request, "Please enter the values in the form field!")
                        return redirect("shop:checkout")

            else:
                messages.info("Please enter valid details!!")
        except:
            pass

        return redirect("shop:payment")


class PaymentView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        
        order = Order.objects.get(user=self.request.user, is_ordered=False)

        if order:
            if order.billing_address:

templates/_order_summary_snippet.html
{% load static %}
<section class="ftco-section ftco-cart">
    <div class="container">
        <div class="row">
            <div class="col-md-12 ftco-animate">
                <div class="cart-list">
                    <table class="table">
                        <thead class="thead-primary">
                            <tr class="text-center">
                                <th>&nbsp;</th>
                                <th>&nbsp;</th>
                                <th>Product</th>
                                <th> Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for cart in cart_items.items.all %}
                        {% comment %} <h1>{{ cart }}</h1> {% endcomment %}
                            <tr class="text-center">
                                <td class="product-remove"><a href={% url 'shop:remove-from-cart' cart.item.slug %}><span class="icon-close"></span></a></td>

                                <td class="image-prod">
                                    <div class="img" style="background-image:url({{ cart.item.image.url }});"></div>
                                </td>

                                <td class="product-name">
                                    <h3>{{ cart.item.title }}</h3>
                                    {% comment %} <p> {{ cart.item.description }}</p> {% endcomment %}
                                </td>

                                <td class="price">${{ cart.item.price }}</td>

                                <td class="quantity">
                                    <div class="input-group mb-3 d-flex justify-content-center align-items-center">
                                        <span data-slug={{ cart.item.slug }} class="decrease"><span class="icon-minus"></span></i></span>

                                        <input type="text" name="quantity" class="quantity item-count form-control input-number mx-2" value={{ cart.quantity }} min="1" max="100">
                                        
                                        <span data-slug={{ cart.item.slug }} class="increase"><span class="icon-plus"></span></i></span>
                                    </div>
                                </td>

                                <td class="total">${{ cart.get_total_item_price }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
</section> 

templates/cart.html
{% extends 'forall/base.html' %}
{% load static %}

{% block pageSpecificCSS %}
<style>
.input-group > .form-control {
    flex-grow: 0;
    width: 50px;
}
.decrease:hover,
.increase:hover {
    cursor:pointer;
}
</style>
{% endblock pageSpecificCSS %}

{% block content %}
<section class="home-slider owl-carousel">
    <div class="slider-item" style="background-image: url({% static 'images/bg_3.jpg' %});" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row slider-text justify-content-center align-items-center">
                <div class="col-md-7 col-sm-12 text-center ftco-animate">
                    <h1 class="mb-3 mt-5 bread">Cart</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href={% url 'core:home' %}>Home</a></span> <span>Cart</span></p>
                </div>
            </div>
        </div>
    </div>
</section>

{% include '_order_summary_snippet.html' %}

<div class="container">
<div class="row justify-content-end">
            <div class="col col-lg-3 col-md-6  cart-wrap ftco-animate">
                <div class="cart-total mb-3">
                    <h3>Cart Totals</h3>
                    <p class="d-flex">
                        <span>Subtotal</span>
                        <span>${{ cart_items.get_cart_total }}</span>
                    </p>
                    <p class="d-flex">
                        <span>Delivery</span>
                        <span>$0.00</span>
                    </p>
                    <p class="d-flex">
                        <span>Discount</span>
                        <span>$0.00</span>
                    </p>
                    <hr>
                    <p class="d-flex total-price">
                        <span>Total</span>
                        <span>${{ cart_items.get_cart_total }}</span>
                    </p>
                </div>
                <p class="text-center"><a href={% url 'shop:checkout' %} class="btn btn-primary py-3 px-4">Proceed to Checkout</a></p>
            </div>
        </div>
</div>

{% include 'forall/_related_products_snippet.html' %}

{% endblock content %}

{% block pageSpecificJS %}
<script>
    $('document').ready(function(){
        const increase = document.querySelector('.increase')
        const decrease = document.querySelector('.decrease')

        const item_count = document.querySelector('.item-count')
        
        increase.addEventListener('click', (event)=>{
            let slug = increase.getAttribute('data-slug')
            let url = '/shop/add-one-to-cart/'+slug
            fetch(url)
                .then(response=>response.json())
                .then(response=>{
                    item_count.value = response.quantity
                })
        })

        decrease.addEventListener('click', (event)=>{
            let slug = increase.getAttribute('data-slug')
            let url = '/shop/remove-one-from-cart/'+slug
            let redirect_url = ''
            fetch(url)
                .then(response=>response.json())
                .then(response=>{
                    item_count.value = response.quantity
                    if(!response.quantity) {
                        window.location.assign("/shop/coffee-machines")
                    }
                })
        })        
    })

</script>
{% endblock %}

templates/checkout.html
{% extends 'forall/base.html' %}
{% load static %}

{% block content %}


<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-xl-8 ftco-animate mt-4">
                <form action="#" id="bill-form" class="billing-form ftco-bg-dark p-3 p-md-5" method="POST">
                {% csrf_token %}
                    <h3 class="mb-4 billing-heading">Billing Details</h3>
                    <div class="row align-items-end">
                        <div class="col-md-12">
                            <div class="form-group mt-4">
                                <div class="radio">
                                    <label class="use-default">
                                    {{ form.use_default }}
                                    Use Default Address </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="firstname">First Name</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="lastname">Last Name</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                        <div class="w-100"></div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="phone">Phone</label>
                                {{ form.phone }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="emailaddress">Email Address</label>
                                {{ form.email }}
                            </div>
                        </div>                    
                        <div class="w-100"></div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="streetaddress">Street Address</label>
                                {{ form.street_name }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                {{ form.apartment }}
                            </div>
                        </div>
                        <div class="w-100"></div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="towncity">Town / City</label>
                                {{ form.city }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="postcodezip">Postcode / ZIP *</label>
                                {{ form.zipcode }}
                            </div>
                        </div>
                        <div class="w-100"></div>
                        <div class="col-md-12 country-col">
                            <div class="form-group">
                                <label for="country">State / Country</label>
                                {{ form.country }}
                            </div>
                        </div>
                        <div class="w-100"></div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="radio">
                                    <label class="set-default-col">
                                    {{ form.set_default }}
                                    Set this as Default
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <p><button href={% url 'shop:payment' %} class="btn btn-primary py-3 px-4 w-100" type="submit">Place an order</button></p>
                        </div>
                    </div>
                </form>
            </div>
            
            <div class="col-xl-4 sidebar ftco-animate">
                <div class="sidebar-box">
                    <div class="cart-detail cart-total ftco-bg-dark p-3 p-md-4">
                        <h3 class="billing-heading mb-4">Cart Total</h3>
                        <p class="d-flex">
                            <span>Subtotal</span>
                            <span>${{ order.get_cart_total }}</span>
                        </p>
                        <p class="d-flex">
                            <span>Delivery</span>
                            <span>$0.00</span>
                        </p>
                        <p class="d-flex">
                            <span>Discount</span>
                            <span>$0.00</span>
                        </p>
                        <hr>
                        <p class="d-flex total-price">
                            <span>Total</span>
                            <span>${{ order.get_cart_total }}</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
<!-- .section -->

{% block pageSpecificJS %}
<script>
   $('#id_use_default').change(()=>{
       $('#bill-form .col-md-6').slideToggle();
       $('.country-col').slideToggle();
       $('.set-default-col').slideToggle();
   })
</script>
{% endblock pageSpecificJS %}

templates/shop.html
{% extends 'forall/base.html' %}
{% load static %}

{% block page_title %}
    Shop
{% endblock page_title %}

{% block pageSpecificCSS %}
<style>
    #v-pills-tabContent {
        width: 100vw;
    }
    .item-title {
        height: 60px;
    }
    .item-desc {
       height: 80px;
    }
    .item-details {
        margin-bottom: 70px;
    }
</style>
{% endblock pageSpecificCSS %}

{% block content %}
<section class="home-slider owl-carousel">
    <div class="slider-item" style="background-image: url({% static 'images/bg_3.jpg' %});" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row slider-text justify-content-center align-items-center">
                <div class="col-md-7 col-sm-12 text-center ftco-animate">
                    <h1 class="mb-3 mt-5 bread">Order Online</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href={% url 'core:home' %}>Home</a></span> <span>Shop</span></p>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="ftco-menu mb-5 pb-5">
    <div class="container">
        <div class="row d-md-flex">
            <div class="col-lg-12 ftco-animate p-md-5">
                <div class="row">
                    <div class="col-md-12 nav-link-wrap mb-5">
                        <div class="nav ftco-animate nav-pills justify-content-center" id="v-pills-tab"  role="tablist" aria-orientation="vertical">
                            {% for category in categories %}
                            <a class="nav-link {% if category_param == category.slug %}active{% endif %}" id="v-pills-3-tab"  href={% url 'shop:shop'  category.slug  %} role="tab" aria-controls="v-pills-3" aria-selected="false">{{ category.title }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-12 d-flex align-items-center">
                        <div class="tab-content ftco-animate" id="v-pills-tabContent">
                            <div class="tab-pane fade show active" id="v-pills-0" role="tabpanel" aria-labelledby="v-pills-0-tab">
                                <div class="row item-wrapper">
                                    {% for item in items %}
                                    <div class="col-lg-3 col-md-4 col-sm-6">
                                        <div class="menu-entry w-100">
                                            <a href={% url 'shop:product_single' item.slug  %} class="img" style="background-image:url({{ item.image.url }}) "></a>
                                            <div class="item-details text text-center pt-4">
                                                <h3 class="item-title"><a href={% url 'shop:product_single' item.slug  %}>{{ item.title | truncatechars:30}}</a></h3>
                                                <p class="item-desc">{{ item.description | truncatechars:80}}</p>
                                                <p class="price"><span>${{ item.price }}</span></p>
                                                <p><a href="{{ item.get_add_to_cart_url }}" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

{% block pageSpecificJS %}
    {% comment %} <script>
        const title = document.title
        let li_a = document.querySelectorAll('.navbar-nav li > a')
        console.log(li_a)
        for( item in li_a ){
            console.log(item.innerText)
        }
    </script> {% endcomment %}
{% endblock pageSpecificJS %}